# Generated by Django 4.2.1 on 2023-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oige_sona', models.CharField(max_length=200)),
                ('sona1', models.CharField(max_length=200)),
                ('sona2', models.CharField(max_length=200)),
                ('sona3', models.CharField(max_length=200)),
                ('sona4', models.CharField(max_length=200)),
                ('sona5', models.CharField(max_length=200)),
            ],
        ),
    ]
