# Generated by Django 4.2.1 on 2023-06-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mang',
            name='sona1',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='mang',
            name='sona2',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='mang',
            name='sona3',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='mang',
            name='sona4',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='mang',
            name='sona5',
            field=models.JSONField(),
        ),
    ]
