# Generated by Django 4.2.1 on 2023-06-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_alter_mang_sona1_alter_mang_sona2_alter_mang_sona3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mang',
            name='sona1',
            field=models.JSONField(default=['     ', 'white', 'white', 'white', 'white', 'white']),
        ),
        migrations.AlterField(
            model_name='mang',
            name='sona2',
            field=models.JSONField(default=['     ', 'white', 'white', 'white', 'white', 'white']),
        ),
        migrations.AlterField(
            model_name='mang',
            name='sona3',
            field=models.JSONField(default=['     ', 'white', 'white', 'white', 'white', 'white']),
        ),
        migrations.AlterField(
            model_name='mang',
            name='sona4',
            field=models.JSONField(default=['     ', 'white', 'white', 'white', 'white', 'white']),
        ),
        migrations.AlterField(
            model_name='mang',
            name='sona5',
            field=models.JSONField(default=['     ', 'white', 'white', 'white', 'white', 'white']),
        ),
    ]
